services:
  - type: web
    name: bengaluru-traffic-backend
    runtime: docker
    plan: free
    branch: deployment
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: GEMINI_API_KEY
        sync: false

